### ISSUE TITLE
Add tsconfig.json to root dir that fixes tests

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snapp-cli#30]
The problem is our dir structure is like this:
```
  /src JS    (this issue)
      templates/project JS   (DONE)
      templates/project-ts TS  (DONE)
```

Tests & CI work in both `project` & `project-ts`; no changes are needed there. 

But `snapp-cli` (`/src` in the schematic above) needs to a `tsconfig.json` added that will allow us to run tests `npm run test` successfully even though JS and TS test files coexist. 

Goal is to run ALL tests (for `/src`,`project`, & `project-ts`), rather than excluding the projects.

**Comment by dillongrove** [comment]
@jasongitmail - Take a look at the above and let me know if this is what you're expecting. If I understand the issue correctly, this can be done via the `transform` option of the jest config (in this case, specified as a key in `package.json`) rather than having to add a new `tsconfig.json`.

Btw, there are one or two warning messages that come up when running this which I think are all benign. Happy to investigate those once we've confirmed that this is the behavior you're expecting.
